version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    networks:
    - selenium_network
    ports:
      - "4444:4444"
    volumes:
      - "$PWD/config:/etc/selenoid/"
      - "$PWD/selenoid-videos:/opt/selenoid/video/"
      - "$PWD/selenoid-logs:/opt/selenoid/logs/"
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
    networks:
    - selenium_network
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

networks:
  selenium_network:
    driver: bridge
    #xcxc